export const FETCH_MOVIE_PAGE_REQUEST = 'FETCH_MOVIE_PAGE_REQUEST';
export const FETCH_MOVIE_PAGE_SUCCESS = 'FETCH_MOVIE_PAGE_SUCCESS';
export const FETCH_MOVIE_PAGE_FAIL = 'FETCH_MOVIE_PAGE_FAIL';
export const PAGE_NEXT = 'PAGE_NEXT';
export const PAGE_PREV = 'PAGE_PREV';
export const FETCH_MOVIE_DETAIL_REQUEST = 'FETCH_MOVIE_DETAIL_REQUEST ';
export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS ';
export const FETCH_MOVIE_DETAIL_FAIL = 'FETCH_MOVIE_DETAIL_FAIL ';

